### ISSUE TITLE
This is happening to me after the last update

### ISSUE THREAD

**Issue by ssanchezhlg** [kingparks/cursor-vip#13]
After the update, some chat responses contain special characters and at the moment it started showing this error when trying to use the chat.

"Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you."

Greetings and thank you very much for your application.

**Comment by wh-sugiharto** [comment]
me too... i gave some probleh here

**Comment by kingparks** [comment]
Fixed, now it has been reduced to 9 people sharing one Pro account, just restart cursor-vip
