### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by TECHGAMESPI** [kingparks/cursor-vip#15]
I have a question, if the time shown on the terminal runs out, will I have to pay something? I still don't quite understand how this works.

**Comment by Jeck-Liu-Create** [comment]
The assignment of a real Pro account to 9 devices does not undermine Cursor's policy requirements

**Comment by kingparks** [comment]
> I have a question, if the time shown on the terminal runs out, will I have to pay something? I still don't quite understand how this works.

Yes, have to
