### ISSUE TITLE
同一个账户用到电脑过多被检测

### ISSUE THREAD

**Issue by 510myRday** [kingparks/cursor-vip#17]
Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you.

**Comment by azeasz** [comment]
same here

**Comment by kingparks** [comment]
解决了，重启cursor-vip 就好了
Solved, just restart cursor-vip
