### ISSUE TITLE
Too many computers

### ISSUE THREAD

**Issue by akuamarin123** [kingparks/cursor-vip#23]
![Screenshot_5](https://github.com/user-attachments/assets/fcd0ad1e-5c0a-4806-91db-31813bc7fc20)

I get an error like this, before that it started to run slowly, I wonder what is the reason and how can I solve thisI get an error like this, before that it started to run slowly, I wonder what is the reason and how can I solve this

**Comment by tianyu924** [comment]
> ![Screenshot_5](https://private-user-images.githubusercontent.com/154087390/394557289-fcd0ad1e-5c0a-4806-91db-31813bc7fc20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODkwOTMsIm5iZiI6MTczMzg4ODc5MywicGF0aCI6Ii8xNTQwODczOTAvMzk0NTU3Mjg5LWZjZDBhZDFlLTVjMGEtNDgwNi05MWRiLTMxODEzYmM3ZmMyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMzQ2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWNiMjFiY2NhYTBjZWMyOTdiNDgwMTIwMjFhN2U0ZWIzZjQ0OTE3YmM0MDEwMDAzMDQzMDJlZGEyYmM4ZDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q9OcFoy83kXoBhbdoMd2_BzKtoTJigjorrtQZGP0lc0)
> 
> I get an error like this, before that it started to run slowly, I wonder what is the reason and how can I solve thisI get an error like this, before that it started to run slowly, I wonder what is the reason and how can I solve this

same question

**Comment by kingparks** [comment]
fixed, rerun cursor-vip can see update
