### ISSUE TITLE
更新最新2.3.0 版本 还是提示 Too many computers 

### ISSUE THREAD

**Issue by gesla2024** [kingparks/cursor-vip#24]
![图片](https://github.com/user-attachments/assets/f5d1c3a2-a66e-4bcc-b61d-cd5d8b7ea4a5)
最新版本突然还是这样 Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you.
![图片](https://github.com/user-attachments/assets/3f4842f4-512a-429d-845a-73f4e7ae7170)

**Comment by kingparks** [comment]
fixed, now can see cursor-vip said “Encountered a problem? Press Enter to restart cursor to resolve the issue”

**Comment by gesla2024** [comment]
好的 谢谢！
