### ISSUE TITLE
**How to know if i have successfully promoted someone**

### ISSUE THREAD

**Issue by cuclacvangsanh** [kingparks/cursor-vip#28]
**How to know if i have successfully promoted someone**
first, your cursor-vip is really awesome, thank you for the free 15 days
I have a trouble when trying to earn some more time to use
I installed cursor-vip on my friend's computer, this is the first time installed it but I don't see my promoted count increase.
please let me know how,

**Comment by kingparks** [comment]
There is currently no place to view it, it is already in my to-do list. You can send me the device codes of both of you and I will check them
