### ISSUE TITLE
Cursor takes too long to respond

### ISSUE THREAD

**Issue by akuamarin123** [kingparks/cursor-vip#29]
![image](https://github.com/user-attachments/assets/9be821f2-6708-410a-8559-8afc923383a7)
cursor's response time has also increased too much, I want something that doesn't come back, it does wrong when it returns, I don't know exactly why the problem is doing this, but it needs to be fixed, and it's been like this for a few days, I've been deleting the cache file, but it doesn't work, I'm using another model, it's coming back to the same state, and then I'm using a low model again, the same

**Comment by ANGLE404** [comment]
You want a stable network environment, and the prompt word is also very important, if the card can try to change your cursor machine code.

**Comment by kingparks** [comment]
sorry composer has wrong
