### ISSUE TITLE
 Too many computers

### ISSUE THREAD

**Issue by gesla2024** [kingparks/cursor-vip#32]
![图片](https://github.com/user-attachments/assets/745871f9-363f-4428-bc1f-a11ce201862e)
![图片](https://github.com/user-attachments/assets/93c09044-a71f-4292-99fb-87057da1b699)
昨天出现重试提示， 点击回车重试后恢复正常了 ，现在页面提示重试，手动重启了 好几回还是这样  Too many computers 提示

**Comment by kingparks** [comment]
fixed
