### ISSUE TITLE
Too many computers used

### ISSUE THREAD

**Issue by CoderHaay** [kingparks/cursor-vip#37]
Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you.

这个问题 有辙吗？

**Comment by kingparks** [comment]
fixed, restart cursor-vip

我会时刻跟着 这样现象快被我找到规律了 会越来越少
