### ISSUE TITLE
Failed By too many computers used within the last 24 hours

### ISSUE THREAD

**Issue by gg1bvcog** [kingparks/cursor-vip#4]
Too many computers used within the last 24 hours for the same Cursor account. Need email to unblock. How to solve this?

**Comment by walkingzzzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kingparks** [comment]
The chat question function is currently not working well, to be fixed; you can use code prompts and code comments to make up for this defect.

**Comment by kingparks** [comment]
> Too many computers used within the last 24 hours for the same Cursor account. Need email to unblock. How to solve this?

目前聊天只能早上人少时能用，只能在代码注释里写 然后用自动补全替代聊天功能

**Comment by kingparks** [comment]
fixed
