### ISSUE TITLE
useless tool now

### ISSUE THREAD

**Issue by BotCoder254** [kingparks/cursor-vip#41]
if you have made this tool user to purchase now is usesless because how comes github is free but your tool someone has to purchase last time i checked github was to provide open source project BRO  ARE YOU HELP USE TO SOLVE ISSUES OR YOU HERE FOR YOUR GAIN

**Comment by zhedream** [comment]
They should be service providers, and many people cannot use up the high-end models. They use technology to achieve account sharing and charge low prices to earn some profits. Opening up this project may be to demonstrate the harmlessness of its services.

**Comment by UshanFernando** [comment]
@BotCoder254 not everything is free in this world

**Comment by BotCoder254** [comment]
> @BotCoder254 not everything is free in this world

BRO if not free what is the aim to have it in Github also you you go for open source things in order to save money for some certain things so dont say that and also your her trying to say not everything

**Comment by kingparks** [comment]
open != free

I also spend money to buy many accounts myself. Currently, sharing one account with 8 devices is sometimes subject to official control, and I cannot persist without income; The current price is 80% off the official website, which is already very cheap and can make Cursor affordable for many people. Although this project is not yet good, I believe that with everyone's support, it will become better and better
