### ISSUE TITLE
软件打开全都提示有新版本实际已经是最新版本

### ISSUE THREAD

**Issue by buaoyezz** [kingparks/cursor-vip#45]
![image](https://github.com/user-attachments/assets/8787f327-3612-4b03-bfcc-d1ac16c56cd7)
如图所示，但是按照Github下载最新文件就是这个，已无更新
包括出现同样问题的还有windsurf-vip
望修复
Windsurf图:
![image](https://github.com/user-attachments/assets/e4de3a14-a403-49d1-8008-1bb716bbb6a5)

**Comment by kingparks** [comment]
目前是 v2.3.2
bash -c "$(curl -fsSLk https://ghp.ci/https://github.com/kingparks/cursor-vip/releases/download/latest/install.sh)"

**Comment by kingparks** [comment]
windsurf-vip 还没做好

**Comment by buaoyezz** [comment]
好的
