### ISSUE TITLE
No more free option?

### ISSUE THREAD

**Issue by itech0307** [kingparks/cursor-vip#47]
Hi, is there no more free option for Cursor Pro? I saw a free option for 2 hours before.
![Screenshot 2024-12-15 132931](https://github.com/user-attachments/assets/6d1f2230-8490-4670-b612-283a0c987fa9)

**Comment by ssanchezhlg** [comment]
Hello, simply close the window and reopen it, it was that it was integrated for the payment on the same terminal.

**Comment by itech0307** [comment]
So it's not free anymore? I followed your method but it only has 1 option which is pay via Paypal

**Comment by anotio** [comment]
Exact same here, reopening don't work.

**Comment by kingparks** [comment]
Yes, the free entrance and backend have been closed
