### ISSUE TITLE
cursor.vip.exe error

### ISSUE THREAD

**Issue by UUmutgamg** [kingparks/cursor-vip#48]
Cursor.vip.exe closes as soon as I click on it. How can I solve this?

**Comment by kingparks** [comment]
v2.3.4 update, reinstall :

bash <(curl -Lk https://github.com/kingparks/cursor-vip/releases/download/latest/i.sh) githubReadme

**Comment by kingparks** [comment]
https://github.com/kingparks/cursor-vip/discussions/44
