### ISSUE TITLE
Missing Dependency for github.com/kingparks/cursor-vip/auth

### ISSUE THREAD

**Issue by aliensb** [kingparks/cursor-vip#5]
Hi,

I noticed that the project is missing the dependency for github.com/kingparks/cursor-vip/auth, which appears to be required for certain parts of the code to compile correctly. Could you please check if this package was unintentionally excluded from the repository or provide guidance on how to resolve this?

Thank you for your attention to this issue, and I look forward to your feedback.

Best regards,

**Comment by walkingzzzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
