### ISSUE TITLE
new update bug on windows

### ISSUE THREAD

**Issue by removespread** [kingparks/cursor-vip#51]
![image](https://github.com/user-attachments/assets/811e70bc-a218-4740-83c3-ab8ea28d56a4)

This bugs seems only on windows users, I didnt' have same on macOS.

**Comment by ssanchezhlg** [comment]
That is not a bug, what it is notifying you is that a new update has been released and you need to download it in order to use it, since the one you have is not compatible with the system.

**Comment by removespread** [comment]
> That is not a bug, what it is notifying you is that a new update has been released and you need to download it in order to use it, since the one you have is not compatible with the system.

okey, so, I tried to do this command.

![image](https://github.com/user-attachments/assets/1ed471c7-13b4-460c-8578-4631afae00b2)
Error: System can't find "cursor-vip.exe" process.

**Comment by kingparks** [comment]
Method 3: Manually download the binary file
