### ISSUE TITLE
promoted 10, but no license

### ISSUE THREAD

**Issue by needitem2** [kingparks/cursor-vip#54]
need time to get 1 year license?

**Comment by kingparks** [comment]
no, show me your DeviceID

**Comment by needitem2** [comment]
ee43a840c9724694a9b57a96dfbcafef

**Comment by needitem2** [comment]
![스크린샷 2024-12-16 154328](https://github.com/user-attachments/assets/20cf404c-4e1e-4229-8a0a-641138312c64)

**Comment by weiguo11** [comment]
caf4cffe8e40414fb3ecb2019fd2c2f0

今天安利给了几个同事

![image](https://github.com/user-attachments/assets/00d40324-63a3-4f68-9362-ad0a74d7dd39)

**Comment by kingparks** [comment]
Hyper-V, VMware, VirtualBox, etc. will be identified as non real users

**Comment by kingparks** [comment]
Hyper-V 、VMware、VirtualBox 等会被识别为非真实的用户
