### ISSUE TITLE
新版本用不了,被cursor限制请求了.

### ISSUE THREAD

**Issue by GuoAccount** [kingparks/cursor-vip#56]
提示:Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you.

我自己用的比较少,这个提示是说多台电脑用的一个cursor账号导致的....

**Comment by kingparks** [comment]
fixed, 设置了自动检测，等cursor-vip 出现 遇到问题？回车重启 时，回车就行

**Comment by asrnline** [comment]
![Image](https://github.com/user-attachments/assets/3493d76c-74d9-4f76-adcb-99b60c4daccc)
