### ISSUE TITLE
在过去24小时内，同一Cursor帐户使用了太多计算机。请稍后重试，

### ISSUE THREAD

**Issue by BoredWait** [kingparks/cursor-vip#59]
Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you

**Comment by kingparks** [comment]
目前普通模式经常报 too many computer,需要等待红字后回车才能解决；
上周末的时候新增了代理模式，在下面连续按键盘 sm2，然后重启下 cursor-vip 可切换到代理模式
(不过有用户反馈sm2模式不能用，如果您也不能用 可以到 Discussions 里讨论)
