### ISSUE TITLE
Error module auth not found

### ISSUE THREAD

**Issue by lucca-rodrigues** [kingparks/cursor-vip#6]
Hi, I'm testting locally project but on install packages i'ts return the error:
       
```
go: finding module for package github.com/kingparks/cursor-vip/auth/sign
go: finding module for package github.com/kingparks/cursor-vip/auth
go: github.com/kingparks/cursor-vip imports
        github.com/kingparks/cursor-vip/auth: no matching versions for query "latest"
go: github.com/kingparks/cursor-vip/tui imports
        github.com/kingparks/cursor-vip/auth/sign: no matching versions for query "latest"
```

It's private module? I'm want to contribute with the project

**Comment by h7ml** [comment]
+1

**Comment by FrankFang** [comment]
Where is auth dir?

**Comment by WANGXIANGSHOUSI** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kingparks/cursor-vip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月10日(星期二) 下午2:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [kingparks/cursor-vip] Error module auth not found (Issue #6)





 
Where is auth dir?

**Comment by kingparks** [comment]
It contains encryption and decryption, and that part is temporarily not planned to be made public. Sorry
