### ISSUE TITLE
Too many computers  等了半个小时 终端都没有变红 提示重启

### ISSUE THREAD

**Issue by Yakumo-Yukari** [kingparks/cursor-vip#61]
Too many computers used within the last 24 hours for the same Cursor account. Please try again later, use a different Cursor account, or contact us at hi@cursor.sh if you believe this is a mistake. We have this limit in place to prevent abuse, but if you have a legitimate use case for using many computers, please do email us and we will unblock you.

**Comment by kingparks** [comment]
目前普通模式经常报 too many computer,需要等待红字后回车才能解决；
上周末的时候新增了代理模式，在下面连续按键盘 sm2，然后重启下 cursor-vip 可切换到代理模式
(不过有用户反馈sm2模式不能用，如果您也不能用 可以到 Discussions 里讨论)

**Comment by kingparks** [comment]
> > 目前普通模式经常报 too many computer,需要等待红字后回车才能解决； 上周末的时候新增了代理模式，在下面连续按键盘 sm2，然后重启下 cursor-vip 可切换到代理模式 (不过有用户反馈sm2模式不能用，如果您也不能用 可以到 Discussions 里讨论)
> 
> sm2模式提示 ![image](https://private-user-images.githubusercontent.com/12076232/396384390-050cfa98-bed2-4e24-ba0f-022460f60311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTk3NTksIm5iZiI6MTczNDQ5OTQ1OSwicGF0aCI6Ii8xMjA3NjIzMi8zOTYzODQzOTAtMDUwY2ZhOTgtYmVkMi00ZTI0LWJhMGYtMDIyNDYwZjYwMzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA1MjQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YjkwODdiMWRjMjk3ZmUxNDNmZGQ2MjQ5MDc0YjIxMmRhNGVjMGViYjY2MmNiZWNkOGNjOWFlYzJmYjFhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H4N1eGv92OvcBUmvC8xAsq6vAYL4joNgToPWPPpatDI)

大部分新开个会话就好 net chat

**Comment by sonemeng** [comment]
重装cursor试试，在官网下载最新版本试试

**Comment by kingparks** [comment]
> > 重装cursor试试，在官网下载最新版本试试
> 
> 我试试

还不行的话留下微信号，准备好 todesk 我上去看看

**Comment by Atestedannas** [comment]
解决了吗？？

**Comment by kingparks** [comment]
> 解决了吗？？

现在只有模式三了，模式三需要不断小额刷新 没有 too many computers 的问题了，只支持auto模型

**Comment by Atestedannas** [comment]
我都还没解决网上的cursor free VIP。和coser。Help我试了都没用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年11月23日(周日) 下午5:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kingparks/cursor-vip] Too many computers  等了半个小时 终端都没有变红 提示重启 (Issue #61)


kingparks left a comment (kingparks/cursor-vip#61)
  
解决了吗？？
  
现在只有模式三了，模式三需要不断小额刷新 没有 too many computers 的问题了，只支持auto模型
