### ISSUE TITLE
代理模式

### ISSUE THREAD

**Issue by rainsubtime** [kingparks/cursor-vip#63]
当我使用代理模式，也添加了证书，依旧提示这个是正常的吗？
![image](https://github.com/user-attachments/assets/95ca8e43-a909-4299-9b60-b8a864108e12)

**Comment by kingparks** [comment]
不正常，应该是证书选错了，选 %homepath%\.cursor-vip\i-need-to-trust-ca-cert.pem

**Comment by rainsubtime** [comment]
解决了~

**Comment by rainsubtime** [comment]
解决了~

**Comment by rainsubtime** [comment]
谢谢
