### ISSUE TITLE
I want to purchase 1 year using paypal.

### ISSUE THREAD

**Issue by ellavondegurechaff** [kingparks/cursor-vip#68]
Hello, my expiration date is nearing:
i want to purchase 1 year using paypal:
DeviceID:a89911a2125c5c37207fdf99e21f3b78

**Comment by ellavondegurechaff** [comment]
anyone here? @kingparks

**Comment by kingparks** [comment]
sure, $30 one year , 8 device shared
paypal: ceo@eiyou.fun

**Comment by kingparks** [comment]
It has been processed. Is it effective? Looking forward to your reply

**Comment by ellavondegurechaff** [comment]
yup it works now, thanks @kingparks !!
