### ISSUE TITLE
无法时使用agent模式

### ISSUE THREAD

**Issue by islenkao** [kingparks/cursor-vip#72]
![image](https://github.com/user-attachments/assets/a33d66ba-62c5-4918-b1c0-5bba9cc55de8)

你们也会遇到这种情况吗？

**Comment by kingparks** [comment]
代理没生效，检查下cursor 的设置里，setting.json 是正常的json文件，可格式化，代理地址为：http://localhost:18030，还不行的话 我可以todesk 看下

**Comment by islenkao** [comment]
![image](https://github.com/user-attachments/assets/e2107e4b-76f1-4b2c-a128-a072e417ca63)
应该是生效的

**Comment by kingparks** [comment]
看起来没问题，加我下微信 我todesk 看下吧 Wx: jetereting

**Comment by islenkao** [comment]
> 看起来没问题，加我下微信 我todesk 看下吧 Wx: jetereting

请您通过一下
