### ISSUE TITLE
The new version of Cursor has been updated

### ISSUE THREAD

**Issue by Ninthless** [kingparks/cursor-vip#73]
The current program is no longer compatible with the latest version of cursor, and there are problems with the application of composer functions. I hope the person in charge will update and adapt it.

**Comment by kingparks** [comment]
I just downloaded it from the official website and found that it's still 0.44.5. Is this the version? This version is compatible

**Comment by Ninthless** [comment]
I found that I caused the cursor problem. Thank you for your answer.
