### ISSUE TITLE
我发现自己的账号登录不上了

### ISSUE THREAD

**Issue by wugengdeliuxi** [kingparks/cursor-vip#75]
现在怎么只能用cursor-vip登录了，自己的账号反而登录不上了，应该怎么做

**Comment by wugengdeliuxi** [comment]
好吧，需要删除cursor-vip
rm -rf ~/.cursor-vip
rm -rf ~/.cursor-viprc

**Comment by kingparks** [comment]
退出cursor-vip 后，不会影响自己账号登录的，检查下是否cursor-vip 没关
