### ISSUE TITLE
Can't use composer

### ISSUE THREAD

**Issue by rainsubtime** [kingparks/cursor-vip#77]
![image](https://github.com/user-attachments/assets/1e59eecf-294f-42d7-af1c-e1c12b13eeb3)
我可以使用chat但是没有办法使用composer以及代码直接edit功能了。提示如图

**Comment by rainsubtime** [comment]
新开个会话是啥意思？点击+号创建新的嘛，但是我这么做也没用，还是说新开个会话是别的意思

**Comment by rainsubtime** [comment]
ok了..我好像开成agent模式了...不过这个模式是不可用的嘛

**Comment by kingparks** [comment]
> ok了..我好像开成agent模式了...不过这个模式是不可用的嘛

对， vip 代理模式中  composer 的 agent 不能用， normal 能用
