### ISSUE TITLE
uninstalled without any apparent reason

### ISSUE THREAD

**Issue by 20240305** [kingparks/cursor-vip#78]
Every time I install 'cursor-vip_windows_amd64.exe', it is uninstalled without any apparent reason immediately afterward. I use Xunlei to download it.

**Comment by kingparks** [comment]
可能是杀毒软件的原因

**Comment by 20240305** [comment]
你好，已收到你的邮件，我将在查看完邮件后尽快回复。

**Comment by 20240305** [comment]
Wow，that`s it.解决了哥们，没啥好回报的给你点个star吧
