### ISSUE TITLE
Cursor do not launch after command view opened

### ISSUE THREAD

**Issue by anotio** [kingparks/cursor-vip#80]
After a few minutes coding with composer, generating code seemed broken, so i closed both Cursor and cursor-vip
After launching vip, nothing happens anymore. Command window appear and all seems to be good, but cursor does not launch.
2.3.7 on win 10 64bits, using exe. Normal mode as i do not understand how to switch to proxy

![Capture](https://github.com/user-attachments/assets/dc733f92-ee9b-43cc-bb2d-c96a3c672353)

**Comment by kingparks** [comment]
This is the end of the trial period and requires purchase
