### ISSUE TITLE
slow request

### ISSUE THREAD

**Issue by VICTOR-f1** [kingparks/cursor-vip#9]
![image](https://github.com/user-attachments/assets/10fe5b9c-1da4-460d-9263-6ced5f73598d)
![image](https://github.com/user-attachments/assets/b6a927d1-4791-40eb-955d-2a224ee09b91)
![image](https://github.com/user-attachments/assets/d9226fe8-8685-4a18-8e32-8f79ccf779ae)
(I did not exhaust the limit, immediately after I sent the request, such a thing appeared)

**Comment by kingparks** [comment]
The advanced AI model server processes slowly, so when there are many people using it, they need to queue up. You can use the small model

**Comment by VICTOR-f1** [comment]
> The advanced AI model server processes slowly, so when there are many people using it, they need to queue up. You can use the small model

okay, I just thought that the pro gives fast requests and this is a bug.
